title: Ahmad Osama Mayad
description:
theme: jekyll-theme-minimal
show_downloads: false
logo: /assets/images/profile.jpg

# Social links
github_username: AhmadOsaMayad

# Build settings
markdown: kramdown
