title: Ahmad Osama Mayad
description: Mobile Application Developer | Flutter Specialist | CS Graduate
theme: jekyll-theme-minimal
show_downloads: false

# Social links
github_username: AhmadOsaMayad

# Build settings
markdown: kramdown
